---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server   
  template:         
    metadata:       
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: pranit007/go-server
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend   
  template:         
    metadata:       
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pranit007/frontend
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---